spring:
  application:
    name:EUREKA
  profiles:
    active: "eureka2"
---
spring:
  profiles: eureka1
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
      
---
spring:
  profiles: eureka2
server:
  port: 8762
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/